### ISSUE TITLE
Model download is slow in OneDrive

### ISSUE THREAD

**Issue by A7eNg** [shanice-l/gdrnpp_bop2022#10]
Dear authors,

Thanks for releasing your excellent work.

I'm reproducing this repo in my own server, but i found that the model files are so large and download from OneDrive is too slow (about 200KB/s), I would be very grateful if you could provide a Baidu cloud link.

Much appreciated your reply in advance!
And congratulations on winning the first place in the bop2022 challenge！

**Comment by shanice-l** [comment]
Thank you for your suggestion. I'll create a mirror at BaiduyunDesk. But it might need some time to upload all the models.

**Comment by shanice-l** [comment]
Done.

**Comment by A7eNg** [comment]
Thank you very much!

**Comment by monajalal** [comment]
@A7eNg would you please be able to share gdrn model with me in Google Drive?
