### ISSUE TITLE
Questions for training separate model for each object and depth refinement

### ISSUE THREAD

**Issue by zuodexin** [shanice-l/gdrnpp_bop2022#107]
Thanks for this awesome project, I have some questions for replication:
1. Are there any scripts for training models for each objects? 
2. After training, how to merge results from different models?  Merging csv files by concat lines?
3. What's the difference between `coordinate-guided depth refinement` of [GPose2023](https://bop.felk.cvut.cz/method_info/410/) and `fast refinement` in this project? Are there any details about `coordinate-guided depth refinement` of [GPose2023](https://bop.felk.cvut.cz/method_info/410/)

**Comment by zuodexin** [comment]
Thanks for this awesome project, I have some questions for replication:
1. Are there any scripts for training models for each objects? 
2. After training, how to merge results from different models?

**Comment by shanice-l** [comment]
Hello.

1. We provided lots of configs for training models for each object.
2. Use scripts in [tools/merge](https://github.com/shanice-l/gdrnpp_bop2022/blob/main/tools/merge_bop_single_obj_results.py)
3. There is a separate branch for coordinate-guided pose refinement. See readme for details.
