### ISSUE TITLE
About the refinement method

### ISSUE THREAD

**Issue by A7eNg** [shanice-l/gdrnpp_bop2022#11]
Dear authors,

Thanks again for your previous reply, but I still have a question, have you tried other refine methods like RNNPose or RePOSE,.etc?If you have tried, how is their performance?

**Comment by shanice-l** [comment]
Sry, we haven’t tried these methods.

**Comment by A7eNg** [comment]
Thanks for your answer, so why you decided to use this refinement method in the beginning, is there some special reason?

**Comment by shanice-l** [comment]
Since coupled iterative refinement is the SOTA refinement method using RGB-D information.

**Comment by A7eNg** [comment]
Thanks very much for your patient reply.
