### ISSUE TITLE
instruction for creation of files such as yolox_x_640_lmo_pbr_lmo_bop_test.json for a synthetic dataset made by BlenderProc

### ISSUE THREAD

**Issue by monajalal** [shanice-l/gdrnpp_bop2022#112]
Hello 

Could you please share how you created the following file for lmo pbr and how to create it for a synthetic dataset made with BlenderProc in BOP format?

`yolox_x_640_lmo_pbr_lmo_bop_test.json` in `datasets/BOP_DATASETS/lmo/test/test_bboxes/yolox_x_640_lmo_pbr_lmo_bop_test.json`

This `json` file is used in `configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py`

**Comment by Corentin-242** [comment]
Hello, did you solved the issue? If yes, how did you do it ?

**Comment by CQUChenC** [comment]
@Corentin-242 @monajalal Hello, I also encountered the same problem. How did you solve it? Could you please share?
