### ISSUE TITLE
training time relevant factors (decreasing training time)

### ISSUE THREAD

**Issue by freLorbeer** [shanice-l/gdrnpp_bop2022#115]
Hi, thanks a lot for your work!

I am trying to train on my own custom data in BOP Format. I used 10k images with around 14k  instances in total of my object of interest (i train only on one single object).

The approximated training time ranges between 8 and 15 days depending on my configurations on batch_size, num_workers, persistent_workers.
But training on the tless dataset on a single object takes around 18-24 hours on the same hardware with around 22k images in the same resolution. 
What are the relevant factors that i miss to improve the training time?  I used the same configuration parameters for my dataset than on the tless dataset.

Can I precompute anything or so?

**Comment by shanice-l** [comment]
Sorry for the late reply. I think there must be some technical problem. GDRNPP training should be much more faster.

**Comment by TrinhNC** [comment]
Hi @freLorbeer , did you find out the problem?

**Comment by freLorbeer** [comment]
Hey @TrinhNC 
Yes the problem was quite simple. Unintentionally, I had an excessive number of training samples, which was an order of magnitude too high :D
By reducing the amount of training data, the training process was as fast as expected.

**Comment by TrinhNC** [comment]
> Hey @TrinhNC 
> Yes the problem was quite simple. Unintentionally, I had an excessive number of training samples, which was an order of magnitude too high :D
> By reducing the amount of training data, the training process was as fast as expected.

Thank you! I will give it a try.
