### ISSUE TITLE
6D pose estimation of small objects

### ISSUE THREAD

**Issue by rahul-martianaut** [shanice-l/gdrnpp_bop2022#118]
What is the achieved benchmark of GDRNPP pose estimation on small objects (23 mm diameter). I currently get an AR of 54% on GDRNPP and 75% AP on YOLOX. Are there ways to improve this result? @shanice-l

**Comment by shanice-l** [comment]
Try to implement the image quality in the process of dynamic zoom-in, rather than bilinear interpolation.
