### ISSUE TITLE
训练之后报错

### ISSUE THREAD

**Issue by 1230678** [shanice-l/gdrnpp_bop2022#125]
Initializing renderer...
Traceback (most recent call last):
  File "/home/eric/gdrnpp1/lib/pysixd/scripts/eval_calc_errors.py", line 216, in <module>
    ren = renderer.create_renderer(width, height, p["renderer_type"], mode="depth")
  File "/home/eric/gdrnpp1/lib/pysixd/scripts/../../../lib/pysixd/renderer.py", line 106, in create_renderer
    return renderer_cpp.RendererCpp(width, height)
  File "/home/eric/gdrnpp1/lib/pysixd/scripts/../../../lib/pysixd/renderer_cpp.py", line 23, in __init__
    self.renderer = bop_renderer.Renderer()
AttributeError: module 'bop_renderer' has no attribute 'Renderer'
Traceback (most recent call last):
  File "lib/pysixd/scripts/eval_pose_results_more.py", line 301, in <module>
    raise RuntimeError("Calculation of pose errors failed.")
RuntimeError: Calculation of pose errors failed.
20240912_185056|WRN|core.gdrn_modeling.engine.test_utils@71: evaluation failed.
  0%|          | 0/1 [00:00<?, ?it/s]20240912_185056|core.gdrn_modeling.engine.test_utils@379: =====================================================================
20240912_185056|core.gdrn_modeling.engine.test_utils@411: ************convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-iter0_lmo-test *********************
20240912_185056|core.gdrn_modeling.engine.test_utils@417: 
objects      mspd_5:50
ape          49.03
can          58.29
cat          69.82
driller      35.65
duck         67.67
eggbox       26.39
glue         48.93
holepuncher  51.60
Avg(8)       50.76
20240912_185056|core.gdrn_modeling.engine.test_utils@411: ************convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-iter0_lmo-test *********************
20240912_185056|core.gdrn_modeling.engine.test_utils@417: 
objects      mssd_0.050:0.500
ape          11.03
can          31.81
cat          31.35
driller      29.55
duck         13.67
eggbox       2.50
glue         33.79
holepuncher  26.10
Avg(8)       22.42
  0%|          | 0/1 [00:00<?, ?it/s]20240912_185056|WRN|core.gdrn_modeling.engine.test_utils@422: output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_/lmo_bop_test/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-iter0_lmo-test/error:vsd_ntop:1_delta:15.000_tau:0.050 does not exist.

20240912_185056|ERR|__main__@233: An error has been caught in function '<module>', process 'MainProcess' (8095), thread 'MainThread' (140481381789824):
Traceback (most recent call last):

> File "./core/gdrn_modeling/main_gdrn.py", line 233, in <module>
    main(args)
    │    └ Namespace(config_file='configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', dist...
    └ <function main at 0x7fc365e24430>

  File "./core/gdrn_modeling/main_gdrn.py", line 199, in main
    Lite(
    └ <class '__main__.Lite'>

  File "/home/eric/anaconda3/envs/ce/lib/python3.8/site-packages/pytorch_lightning/lite/lite.py", line 408, in _run_impl
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', dis...
           └ functools.partial(<bound method LightningLite._run_with_strategy_setup of <__main__.Lite object at 0x7fc45ec55e20>>, <bound m...
  File "/home/eric/anaconda3/envs/ce/lib/python3.8/site-packages/pytorch_lightning/lite/lite.py", line 413, in _run_with_strategy_setup
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', dis...
           └ <bound method Lite.run of <__main__.Lite object at 0x7fc45ec55e20>>

  File "./core/gdrn_modeling/main_gdrn.py", line 189, in run
    return self.do_test(cfg, model)
           │    │       │    └ _LiteModule(
           │    │       │        (_module): GDRN_DoubleMask(
           │    │       │          (backbone): FeatureListNet(
           │    │       │            (stem_0): Conv2d(3, 128, kernel_size=(4, 4),...
           │    │       └ Config (path: configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_ROOT...
           │    └ <function GDRN_Lite.do_test at 0x7fc36618f0d0>
           └ <__main__.Lite object at 0x7fc45ec55e20>

  File "/home/eric/gdrnpp1/core/gdrn_modeling/../../core/gdrn_modeling/engine/engine.py", line 159, in do_test
    results_i = gdrn_inference_on_dataset(cfg, model, data_loader, evaluator, amp_test=cfg.TEST.AMP_TEST)
                │                         │    │      │            │                   └ Config (path: configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_ROOT...
                │                         │    │      │            └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7fc3d5929250>
                │                         │    │      └ <pytorch_lightning.lite.wrappers._LiteDataLoader object at 0x7fc3d57a0280>
                │                         │    └ _LiteModule(
                │                         │        (_module): GDRN_DoubleMask(
                │                         │          (backbone): FeatureListNet(
                │                         │            (stem_0): Conv2d(3, 128, kernel_size=(4, 4),...
                │                         └ Config (path: configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_ROOT...
                └ <function gdrn_inference_on_dataset at 0x7fc3661d0dc0>

  File "/home/eric/gdrnpp1/core/gdrn_modeling/../../core/gdrn_modeling/engine/gdrn_evaluator.py", line 804, in gdrn_inference_on_dataset
    results = evaluator.evaluate()  # results is always None
              │         └ <function GDRN_Evaluator.evaluate at 0x7fc3661e6d30>
              └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7fc3d5929250>

  File "/home/eric/gdrnpp1/core/gdrn_modeling/../../core/gdrn_modeling/engine/gdrn_evaluator.py", line 584, in evaluate
    return self._eval_predictions()
           │    └ <function GDRN_Evaluator._eval_predictions at 0x7fc3661e6dc0>
           └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7fc3d5929250>

  File "/home/eric/gdrnpp1/core/gdrn_modeling/../../core/gdrn_modeling/engine/gdrn_evaluator.py", line 595, in _eval_predictions
    save_and_eval_results(self.cfg, results_all, self._output_dir, obj_ids=self.obj_ids)
    │                     │    │    │            │    │                    │    └ [1, 5, 6, 8, 9, 10, 11, 12]
    │                     │    │    │            │    │                    └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7fc3d5929250>
    │                     │    │    │            │    └ 'output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_/lmo_bop_test'
    │                     │    │    │            └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7fc3d5929250>
    │                     │    │    └ {'iter0': [{'scene_id': '2', 'im_id': 3, 'obj_id': 1, 'score': tensor(0.0522, dtype=torch.float64), 'R': [0.8363087177276611,...
    │                     │    └ Config (path: configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_ROOT...
    │                     └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7fc3d5929250>
    └ <function save_and_eval_results at 0x7fc3661e6160>

  File "/home/eric/gdrnpp1/core/gdrn_modeling/../../core/gdrn_modeling/engine/test_utils.py", line 73, in save_and_eval_results
    load_and_print_val_scores_tab(
    └ <function load_and_print_val_scores_tab at 0x7fc3661e6790>

  File "/home/eric/gdrnpp1/core/gdrn_modeling/../../core/gdrn_modeling/engine/test_utils.py", line 423, in load_and_print_val_scores_tab
    raise RuntimeError("{} does not exist.".format(score_root))
                                                   └ 'output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_/lmo_bop_test/convnext...

RuntimeError: output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_/lmo_bop_test/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-iter0_lmo-test/error:vsd_ntop:1_delta:15.000_tau:0.050 does not exist.

在lmo数据集上训练，报上述错误，应该与bop_render相关，但是已经安装和编译通过了，用脚本测试时也报错：AttributeError: module 'bop_renderer' has no attribute 'Renderer'，求解决方案。

**Comment by wangg12** [comment]
https://github.com/shanice-l/gdrnpp_bop2022/issues/32

**Comment by 1230678** [comment]
@wangg12 您好，我将bop_renderer安装在了gdrnpp下，之前也试过软链接，但是训练之后报错AttributeError: module 'bop_renderer' has no attribute 'Renderer'

**Comment by 1230678** [comment]
我在考虑是不是因为编译生成的.so文件是py36,而我的环境是python3.8
