### ISSUE TITLE
Failed to compile uncertainty_pnp on ubuntu 20.04 using compile_all.sh

### ISSUE THREAD

**Issue by GiantRabbit12138** [shanice-l/gdrnpp_bop2022#126]
Hi, could you please help me with the following issue? @wangg12 @goodfella47 @Rainbowend @lolrudy @tzsombor95 
When I compile using the compile_all.sh script, uncertainty_pnp failed to compile successfully. I'm using Ubuntu version 20.04. The error screenshot is as follows:
![image](https://github.com/user-attachments/assets/575dcc25-f735-4fda-8b13-0b6d455ecb42)
![image](https://github.com/user-attachments/assets/826d6f5e-6952-41ca-b7c8-95024114484e)

**Comment by tzsombor95** [comment]
@GiantRabbit12138 Maybe your gcc version is not compatible with this code. Try to use 5.4.0 gcc version.

**Comment by GiantRabbit12138** [comment]
> @GiantRabbit12138 Maybe your gcc version is not compatible with this code. Try to use 5.4.0 gcc version.

@tzsombor95 Thank you for your reply! According to your suggestion, I replaced the original `gcc 9.4.0` with `gcc 5.4.0`. However, the previous error in compiling `uncertainty_pnp` did not disappear. In addition, packages such as` flow` and `ransac_voting` also prompt that the gcc version is too low. In fact, the two errors reported by gcc before only appeared when compiling `uncertainty_pnp` (i.e.` gcc: error: ./lib/libceres.so: No such file or directory` and `gcc: error: ./lib/libglog.so: No such file or directory`) Could you please give me some other suggestions? By the way, my operating system is `ubuntu22.04`, `python` version is 3.8, `cuda` version is 11.6, and `pytorch` version is 1.13.1.
![image](https://github.com/user-attachments/assets/b4d4a3c3-fe9e-407b-8113-73778967e974)
![image](https://github.com/user-attachments/assets/25c8a6c4-1abb-4a74-8628-64ce2034c98f)
![image](https://github.com/user-attachments/assets/e809ef19-768b-4282-b5e4-6ea109c07b04)

**Comment by tzsombor95** [comment]
@GiantRabbit12138 I checked my environment, I have 9.4.0 gcc, so it was a good start. Did you run scripts/install_deps.sh before compile_all.sh script?

**Comment by GiantRabbit12138** [comment]
> @GiantRabbit12138 I checked my environment, I have 9.4.0 gcc, so it was a good start. Did you run scripts/install_deps.sh before compile_all.sh script?

@tzsombor95 Yes, in order to avoid ignoring some wrong installation information, I executed the installation command line by line([install_depth.sh](https://github.com/shanice-l/gdrnpp_bop2022/blob/8c6c34b1705008c6798f921dc5609f1e77f045e2/scripts/install_deps.sh)). However, `uncertainty_pnp` still failed to compile successfully. Then I started to look at the error content of `gcc`. It showed that it would use two dynamic library files in the `./lib` folder during compilation, but I did not find these two files in the `./lib` folder. So I would like to ask how to generate these two files.
![image](https://github.com/user-attachments/assets/dbb28549-94a5-42f0-ab2b-097d0996bf90)
However, if this was a common problem, I might have found it in the `issue`, but I didn't find the same problem as mine in the `issue`, which makes me wonder if there is another reason causing this problem.

**Comment by tzsombor95** [comment]
Try to follow this instructions: [https://github.com/shanice-l/gdrnpp_bop2022/blob/main/docs/INSTALL.md](url)
At the end of this doc, there is a how to install uncertainty pnp (for pvnet)

**Comment by GiantRabbit12138** [comment]
> Try to follow this instructions: [https://github.com/shanice-l/gdrnpp_bop2022/blob/main/docs/INSTALL.md](url) At the end of this doc, there is a how to install uncertainty pnp (for pvnet)

@tzsombor95 Thank you, sir. Following the steps in [INSTALL.md](https://github.com/shanice-l/gdrnpp_bop2022/blob/8c6c34b1705008c6798f921dc5609f1e77f045e2/docs/INSTALL.md), I successfully generated the libceres.so file. As for `libglog.so`, I used the `whereis` command to find its directory and created a symbolic link using the `sudo ln -s` command. Finally, I created a `lib` directory under the `uncertainty_pnp` directory and placed these two files in it. The compilation did not report any errors in the end.
The compilation result of the `uncertainty_pnp` library is:
```text
generating ./_ext.c
(already up-to-date)
the current directory is '/root/gdrnpp_bop2022/core/csrc/uncertainty_pnp'
running build_ext
building '_ext' extension
gcc -pthread -B /root/miniconda3/envs/myconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/miniconda3/envs/myconda/include/python3.8 -c _ext.c -o ./_ext.o
gcc -pthread -shared -B /root/miniconda3/envs/myconda/compiler_compat -L/root/miniconda3/envs/myconda/lib -Wl,-rpath=/root/miniconda3/envs/myconda/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_ext.o src/uncertainty_pnp.cpp.o ./lib/libceres.so ./lib/libglog.so -lstdc++ -o ./_ext.cpython-38-x86_64-linux-gnu.so
```
![image](https://github.com/user-attachments/assets/51f8dce7-75f8-4095-a41b-dfac9f679a16)

**Comment by wangg12** [comment]
You do not need uncertainty_pnp for gdrnpp
