### ISSUE TITLE
Where should I get the xyz_crop directory of lmo datasets?

### ISSUE THREAD

**Issue by Aljen-511** [shanice-l/gdrnpp_bop2022#128]
Hi, I'm _new_ in the research of pose estimation, and I downloaded the lmo dataset from huggingface (followed the guidence of official BOP website). 
The wired thing is, when I tried to train a model on that dataset, I found no `xyz_crop` directory under lmo's trainset, while the python script `./core/gdrn_modeling/datasets/lm_pbr.py` does define a  path parameter pointed to that directory (line 354). The training script I used is as below: 
```bash
$ ./core/gdrn_modeling/train_gdrn.sh configs/gdrn/lmoPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_lmo/duck.py 0
```
By the way, It seems that the class `LM_PBR_Dataset` DO NOT take measures to handle the `lmo` case, as the PNG format of `lmo`'s rgb images is not considered (line 113). Is it a BUG or did I run the script in a wrong way?

**Comment by Aljen-511** [comment]
I also notice that `issue #123` has the same problem, but didn't give a solution.

**Comment by Aljen-511** [comment]
I also notice that `issue #123` has the same problem, but didn't give a solution.

**Comment by Aljen-511** [comment]
我在#23我找到类似问题的解决方案。
但是训练gdrn的时候，可以像训练yolox一样注释掉`assert assert osp.exists(xyz_path)`吗？

**Comment by shanice-l** [comment]
Yes. You can directly remove assert osp.exists(xyz_path). It is not necessary with online rendering.

**Comment by shanice-l** [comment]
LMO整个是一个测试集，没有真实图片作为训练，可以在lm_pbr/lmo_pbr上训练，再在LMO上做evaluation。

**Comment by Aljen-511** [comment]
好的好的，谢谢回复😭
