### ISSUE TITLE
403 forbidden when downloading ycbv dataset 

### ISSUE THREAD

**Issue by sjtuytc** [shanice-l/gdrnpp_bop2022#19]
wget http://ptak.felk.cvut.cz/6DB/public/bop_datasets/ycbv_models.zip
--2022-12-07 17:34:55--  http://ptak.felk.cvut.cz/6DB/public/bop_datasets/ycbv_models.zip
Resolving proxy.cse.cuhk.edu.hk (proxy.cse.cuhk.edu.hk)... 137.189.90.241, 137.189.90.217, 137.189.88.229
Connecting to proxy.cse.cuhk.edu.hk (proxy.cse.cuhk.edu.hk)|137.189.90.241|:8000... connected.
Proxy request sent, awaiting response... 403 Forbidden
2022-12-07 17:34:55 ERROR 403: Forbidden.

**Comment by wangg12** [comment]
It seems the link is not correct. it should be https://bop.felk.cvut.cz/media/data/bop_datasets/ycbv_models.zip
