### ISSUE TITLE
visualize reuslts

### ISSUE THREAD

**Issue by huiwenzhang** [shanice-l/gdrnpp_bop2022#22]
Hi, 
I want to quickly test the model without dive into details. Everything is fine. the pre-trained model is successfully loaded and the evaluation is done correctly. However,  the numbers are not intuitive and I didn't figure out how to visualize the results. Can U explain it a little bit? Besides, there are a lot of configurations for this repo, it might be better to explain some of the params in detail.
Thx

**Comment by shanice-l** [comment]
We provided visualization scripts for each dataset, e.g. [YCB-V](https://github.com/shanice-l/gdrnpp_bop2022/blob/main/core/gdrn_modeling/tools/ycbv/ycbv_3_vis_poses_full.py).
You can change the pred_path and vis_dir to your output path.

**Comment by george66s** [comment]
Hi Shanice,

尝试跑你上面提到的 gdrnpp_bop2022/core/gdrn_modeling/tools/ycbv/ycbv_3_vis_poses_full.py，出现了下面的错误提示：

FileNotFoundError: [Errno 2] No such file or directory: 'output/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_ycbv_real_pbr_visib20_20e_allObjs/a6-cPnP-AugAAETrunc-BG0.5-ycbv-real-pbr-visib20-20e-singleObjMerged-bop-test-iter0_ycbv-test.csv'

抱歉有一些lost，这个文件是由训练生成的吗？我们可以不跑训练直接跑这个程序吗？

谢谢！
George

**Comment by wangg12** [comment]
这个应该是测试结果文件，可以改成您自己的测试文件。@shanice-l 可以考虑是否把写死的路径可以改成命令行参数

**Comment by george66s** [comment]
王博，

感谢反馈。看我的理解对不对？在visualize前需要先跑一下测试（test）。test会产生上面的.csv文件，这样就可以用ycbv_3_vis_poses_full.py 来图形化显示pose的结果了。如果这个理解是正确的，那么这个issue可以close了。ycbv_3_vis_poses_full.py 这个程序我可以自己修改一下。

非常感谢！
George

**Comment by huiwenzhang** [comment]
@george66s need to run the test script first, and the csv file will be generated under the output directory. Finally, visualize the result use the script mentioned above.  I use the LMO dataset, the visualization script needs a .pkl model, however only pth model are provided in this repo @shanice-l . I am testing the YCB-V dataset now, @george66s where did you get the dataset? The original dataset seems to be very large(+200G), and the BOP website said they made some modifications to this dataset, but I can't find the modified version.

**Comment by huiwenzhang** [comment]
> @george66s need to run the test script first, and the csv file will be generated under the output directory. Finally, visualize the result use the script mentioned above. I use the LMO dataset, the visualization script needs a .pkl model, however only pth model are provided in this repo @shanice-l . I am testing the YCB-V dataset now, @george66s where did you get the dataset? The original dataset seems to be very large(+200G), and the BOP website said they made some modifications to this dataset, but I can't find the modified version.

Update: I download the YCB-V dataset from the BOP website, and the data is arranged by following the BOP format. However, when running the test,  throws error `no directory **ycbv/image_set/ exists` for the ycbv dataset.

**Comment by shanice-l** [comment]
Download image_set from our provided path. Plz see the readme.md for details.

**Comment by shanice-l** [comment]
> the

The .pkl file will be generated once the inference ends. It's the file that records the predicted pose.

**Comment by george66s** [comment]
@huiwenzhang ycbv数据集的下载地址：https://bop.felk.cvut.cz/datasets/

**Comment by george66s** [comment]
@wangg12 @shanice-l ，非常感谢两位的回答。现在清楚很多了。

George

**Comment by george66s** [comment]
@huiwenzhang 可以从百度网盘下载image_set。https://pan.baidu.com/share/init?surl=gGoZGkuMYxhU9LBKxuSz0g password: qjfk

**Comment by huiwenzhang** [comment]
> @huiwenzhang 可以从百度网盘下载image_set。https://pan.baidu.com/share/init?surl=gGoZGkuMYxhU9LBKxuSz0g password: qjfk

it works, thx

**Comment by huiwenzhang** [comment]
> 

Good to know. I checked the code, it saves predicted poses in a CSV file instead of a pkl file. I modified the visualization script to read from csv, and it works fine

**Comment by freLorbeer** [comment]
@shanice-l  You mentioned, that you implemented visualization scripts for each dataset. 
I can't find a script for the tless dataset. What do I have to modify in the given scripts that it can be used for tless?
