### ISSUE TITLE
Missing lmo/train_pbr/xyz_crop/000000/000000_000006-xyz.pkl

### ISSUE THREAD

**Issue by george66s** [shanice-l/gdrnpp_bop2022#23]
王博，刘博，

请教一个问题。在跑yolox的训练的时候，使用下面的训练命令来训练 lmo的数据集，出现了找不到文件的错误：

main_yolox.py --config-file configs/yolox/bop_pbr/yolox_x_640_augCozyAAEhsv_ranger_30_epochs_lmo_pbr_lmo_bop_test.py --num-gpus 1

AssertionError: /home/t3080/workspace_Pose/gdrnpp_bop2022/datasets/BOP_DATASETS/lmo/train_pbr/xyz_crop/000000/000000_000006-xyz.pkl

在GDR-Net的开源里面，xyz_crop是另外下载的。这里的 xyz_crop 还需要另外下载吗？还是项目里有工具可以生成？

谢谢！
George

**Comment by george66s** [comment]
看了其他的issues，尝试了用GDR-Net的GDR-Net/tools/lm/lm_pbr_1_gen_xyz_crop.py 来生成上面需要的文件。在对代码做了一些修改后，确实可以生成datasets/BOP_DATASETS/lmo/train_pbr/xyz_crop/000000/000000_000006-xyz.pkl 以及其他类似的文件。能否确认一下这种方法是不是可行的方法？生成的文件是正确可以使用的文件是吗？

谢谢！
George

**Comment by george66s** [comment]
根据王博在 https://github.com/shanice-l/gdrnpp_bop2022/issues/15 里面提到的，“Training with pre-generated coordinates is also possible by disabling the option, but it might not be well supported since we have stopped maintaining this feature for a long time. Saving the coordinates on the disk also needs a huge amount of storage space.”。这里好像产生了一个左右为难的问题。从生成的xyz_crop数据看，确实文件很大，仅一个lmo的xyz_crop就可能占了90G的空间。但是 main_yolox.py 在训练lmo数据集的时候不是online来生成xyz_crop的。如果不事先生成lmo数据集的xyz_crop数据，main_yolox.py就无法训练lmo. 所以我的问题是：

1）main_yolox.py 有什么办法可以绕过，不先生成 xyz_crop 数据，就能够直接训练 lmo 数据集吗？
2）GDR-Net开源项目曾经提供了下载的xyz_crop数据。一个有趣的现象是，这个下载的xyz_crop的数据量大约仅是用lm_pbr_1_gen_xyz_crop.py 产生的数据量的十分之一到二十分之一。能解释一下这个现象吗？是否对lm_pbr_1_gen_xyz_crop.py 程序进行一定的修改，也可以产生同样仅现在十分之一或二十分之一的少得多的数据？这样是不是就可以解决这个左右为难的问题了？

非常感谢！
George

**Comment by wangg12** [comment]
理论上yolox是不依赖xyz的，可能导入数据的代码里之前写了没有改，@Rainbowend 可以check一下

**Comment by shanice-l** [comment]
代码里有一句assert xyz_path is not None，删掉就可以了，不影响实验

**Comment by george66s** [comment]
好的。谢谢啦！

George

**Comment by usersssssssssssss** [comment]
> 看了其他的issues，尝试了用GDR-Net的GDR-Net/tools/lm/lm_pbr_1_gen_xyz_crop.py 来生成上面需要的文件。在对代码做了一些修改后，确实可以生成datasets/BOP_DATASETS/lmo/train_pbr/xyz_crop/000000/000000_000006-xyz.pkl 以及其他类似的文件。能否确认一下这种方法是不是可行的方法？生成的文件是正确可以使用的文件是吗？
> 
> 谢谢！乔治
请问如何修改的代码生成的datasets/BOP_DATASETS/lmo/train_pbr/xyz_crop/000000/000000_000006-xyz.pkl 以及其他类似的文件？非常感谢！
