### ISSUE TITLE
yolox训练和后续的训练次序

### ISSUE THREAD

**Issue by george66s** [shanice-l/gdrnpp_bop2022#24]
Hi Shanice,

用yolox跑ycbv的数据集是可以立刻就跑起来的。在batch_size = 8 (GPU: RTX3080Ti, 12G)的设置下，需要的时间大概1天多。Batch_size = 16 会导致GPU内存溢出。请教几个问题：

1）yolox训练是一个必须的先期步骤吗？
2）yolox训练完成后，在进入正式的pose训练前，还需要再先进行其他的数据预处理步骤吗？比如有些数据集的训练（lmo），需要xyz_crop的数据。每个数据集的 farthest point sampling 也需要预先处理好吗？
3）整个训练的步骤似乎比较多，能否给一个更详细的全过程训练步骤？

非常感谢！
George

**Comment by wangg12** [comment]
1) yolox和pose训练是可以独立的，pose的测试需要以来yolox的测试结果

2) fps是需要先生成的

3) @shanice-l 有时间可以加一下文档

**Comment by shanice-l** [comment]
(1) 可以不用训练YOLOX，直接下载我们提供的test bboxes
(2) xyz_crop的数据是在线渲染的，所以不需要额外生成

**Comment by george66s** [comment]
王博，刘博，

非常感谢！

我close这个issue了。

George
