### ISSUE TITLE
KeyError: timm/convnext_base 不存在

### ISSUE THREAD

**Issue by george66s** [shanice-l/gdrnpp_bop2022#25]
王博，刘博，

在训练开始前建立神经网络模型的时候，系统返回一个错误，BACKBONES这个辞典里面找不到 timm/convnet_base这个键值。

我查了一下代码。在requirements.txt 里面，下载安装的是最新版的 timm。我这里的timm的版本是 0.8.2.dev0. 这个版本的 timm 没有单独存在的 convnext_base，而是有四个分支：
'timm/convnext_base.fb_in1k'
'timm/convnext_base.fb_in22k'
'timm/convnext_base.fb_in22k_ft_in1k'
'timm/convnext_base.fb_in22k_ft_in1k_384'

你们建议用哪个做为backbone? 

谢谢！
George

**Comment by shanice-l** [comment]
升级一下timm的版本即可

**Comment by george66s** [comment]
你们的timm是哪个版本啊？

**Comment by shanice-l** [comment]
我使用的是0.6.7

**Comment by george66s** [comment]
确实是timm的版本问题。删除原来环境里的timm, 重新安装了一下，版本是 0.6.12. 问题就解决了。我看到在 requirements.txt 里面有这样的内容：

# timm  # pytorch-image-models
git+ssh://git@github.com/rwightman/pytorch-image-models.git  # the latest timm

不知道我原来环境里面的 timm 是不是通过这条安装近来的。如果是的话，可能其他人也会遇到同样的问题。

Thanks
George

**Comment by shanice-l** [comment]
谢谢您的提醒，文件已经修改。
