### ISSUE TITLE
Potential dataset issue

### ISSUE THREAD

**Issue by george66s** [shanice-l/gdrnpp_bop2022#26]
王博，刘博，

在 loading dataset dicts: ycbv_train_real 完成后，出现下面的警告：

20230111_114259|WRN|core.gdrn_modeling.datasets.ycbv_d2@276: Filtered out 2716 instances without valid box. There might be issues in your dataset generation process.

Filtered out 2716 instances without valid box 是什么含义能解释一下吗？这个对后续的训练有影响吗？

谢谢！
George

**Comment by wangg12** [comment]
这是正常的，过滤掉了可见部分太少甚至不可见的物体

**Comment by george66s** [comment]
也就是说，由于存在这些可见部分太少甚至不可见的物体，程序才提醒数据集的建立过程可能存在问题。理解了，非常感谢！

George
