### ISSUE TITLE
Pose Refinement Error

### ISSUE THREAD

**Issue by jrahim** [shanice-l/gdrnpp_bop2022#27]
Hi, there are  few issues with refinement. First issue has already been reported (key error: ["coord_x"]). I resolved that by adding "or cfg.TEST.USE_DEPTH_REFINE" on line 203 of GRDN_double_mask. I now have another issue:
```

File "/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/gdrn_evaluator.py", line 543, in process_depth_refine
    query_img_norm = query_img_norm.numpy() * ren_mask * depth_sensor_mask_crop
                     │              │         │          └ array([[False, False, False, ...,  True,  True,  True],
                     │              │         │                   [False, False, False, ...,  True,  True,  True],
                     │              │         │                   [False...
                     │              │         └ array([[False, False, False, ..., False, False, False],
                     │              │                  [False, False, False, ..., False, False, False],
                     │              │                  [False...
                     │              └ <method 'numpy' of 'torch._C._TensorBase' objects>
                     └ tensor([[0.0402, 0.0875, 0.1061,  ..., 0.1182, 0.1044, 0.0653],
                               [0.0913, 0.1657, 0.1896,  ..., 0.2083, 0.1792, 0.1090...

ValueError: operands could not be broadcast together with shapes (64,64) (256,256) 
```

It seems that the depth_sensor_mask crop is (256,256), while the other two tensors are (64,64)

how do I solve this?

**Comment by Martin9797** [comment]
I am getting the same error when adding "or cfg.TEST.USE_DEPTH_REFINE", and without that I get the "coor_x"  error. I'd be  interested in a way to solve this too

**Comment by tzsombor95** [comment]
I managed to solve this by resize the depth_sensor_crop, and it seems working fine.
# depth_sensor_crop = _input['roi_depth'][inst_i].cpu().numpy().copy().squeeze()
depth_sensor_crop = cv2.resize(_input['roi_depth'][inst_i].cpu().numpy().copy().squeeze(), (64, 64))

**Comment by mqtjean** [comment]
Thank you @tzsombor95, its seems working fine for me too.
