### ISSUE TITLE
keypoints_3d.pkl not found

### ISSUE THREAD

**Issue by gonalo99** [shanice-l/gdrnpp_bop2022#34]
In order to visualize the test results, the code accesses the function get_keypoints_3d, in the ref folder (example below is for the lm dataset)

```
def get_keypoints_3d():
    """key is str(obj_id) generated by
    core/roi_pvnet/tools/lm/lm_1_compute_keypoints_3d.py."""
    keypoints_3d_path = osp.join(model_dir, "keypoints_3d.pkl")
    assert osp.exists(keypoints_3d_path), keypoints_3d_path
    kpts_dict = mmcv.load(keypoints_3d_path)
    return kpts_dict
```

However, the path provided in the function "core/roi_pvnet/tools/lm/lm_1_compute_keypoints_3d.py" doesn't exist, so I can't generate the keypoints_3d.pkl file nor does it exist.

How can I generate this file to visualize the estimated poses?

**Comment by shanice-l** [comment]
Sry for the late reply. I've uploaded the [code ](https://github.com/shanice-l/gdrnpp_bop2022/blob/main/core/gdrn_modeling/tools/lmo/lmo_1_compute_keypoints_3d.py) for computing keypoints, so you can generate the file by yourself.
