### ISSUE TITLE
compile about the egl_renderer

### ISSUE THREAD

**Issue by ustblogistics87** [shanice-l/gdrnpp_bop2022#35]
您好，在搭建环境的时候编译egl_renderer时遇到报错：
![image](https://user-images.githubusercontent.com/50019289/220117110-83695a1a-d0e4-470a-b358-c4f8ec2a2709.png)
系统环境：ubuntu16.04
期望得到您的指导！

**Comment by sdu-huanhq** [comment]
请问您解决了吗？我也遇到了相同的问题

**Comment by ustblogistics87** [comment]
> 请问您解决了吗？我也遇到了相同的问题

没有解决呢，请问您解决了吗

**Comment by sdu-huanhq** [comment]
问题已解决：
使用Ubuntu20.04系统，cmake最新版增加了查询opengl的功能，但16.04不太好安装cmake最新版（即3.26.0）。目前在20.04系统中已成功运行训练程序

**Comment by sdu-huanhq** [comment]
当然你们可以尝试在16.04中安装cmake3.26.0，但不一定成功，即便成功也不一定可以顺利编译：）

**Comment by shanice-l** [comment]
不推荐使用16.04，我们没在上面跑过实验，不太清楚环境可能有什么问题。

**Comment by ustblogistics87** [comment]
解决方案，ubuntu16.04系统安装最新版cmake(3.26.0)
并且检查libGL的软链接
sudo find /usr/lib/ -name libGL.so*
ln -s /usr/lib/x86_64-linux-gnu/mesa/libGL.so libGL.so

**Comment by ustblogistics87** [comment]
> 问题已解决： 使用Ubuntu20.04系统，cmake最新版增加了查询opengl的功能，但16.04不太好安装cmake最新版（即3.26.0）。目前在20.04系统中已成功运行训练程序

您好，借着请问一下，我用两张rtx3090训练ycbv数据集，参数config为IMS_PER_BATCH=48,TOTAL_EPOCHS=40 训练时长显示需要14天。同样用两张3090训练tless数据集，将TOTAL_EPOCHS改为8，同样需要2天的时间才能够训练完，可能是由于epoch不够，测试结果和官方提供的结果差异很大。
请问这样的训练时长是正常的嘛

**Comment by guan2000910** [comment]
> 解决方案，ubuntu16.04系统安装最新版cmake(3.26.0) 并且检查libGL的软链接 sudo find /usr/lib/ -name libGL.so* ln -s /usr/lib/x86_64-linux-gnu/mesa/libGL.so libGL.so

您好，我使用软链接还是显示无法找到opengl，请问您对cmakelist有修改吗

**Comment by ustblogistics87** [comment]
> > 解决方案，ubuntu16.04系统安装最新版cmake(3.26.0) 并且检查libGL的软链接 sudo find /usr/lib/ -name libGL.so* ln -s /usr/lib/x86_64-linux-gnu/mesa/libGL.so libGL.so
> 
> 您好，我使用软链接还是显示无法找到opengl，请问您对cmakelist有修改吗
有的我在cmakelists增加了set(OPENGL_opengl_LIBRARY  /usr/lib/x86_64-linux-gnu/libGL.so)
软链接这部分可能是系统的路径不对或者是链接失效，需要确认下路径
