### ISSUE TITLE
训练参数的疑问

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#39]
王博、刘博你们好：

请问配置文件中的```XYZ_CLASS_AWARE=True, MASK_CLASS_AWARE=True, REGION_CLASS_AWARE=True```这三个训练参数是什么意思呢？我的理解是是否需要估计xyz map, mask和region中每个pixel所属的类别。请问这种理解是否正确？如果正确的话，还有另一个疑问：

在Double mask GDRNPP中，输入到ConvNext中的是由目标检测网络裁剪出来的部分并resize为256，也就是所输入到ConvNext的图像中是包含物体的类别信息的（在你们提供的text_box中也可以看到），那么按理说就不需要估计每个像素的类别，只需要区分出背景和前景即可。但配置文件中的仍是```XYZ_CLASS_AWARE=True, MASK_CLASS_AWARE=True, REGION_CLASS_AWARE=True```，请问这是为什么呢？

上述的配置文件为```./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py```

**Comment by wangg12** [comment]
区别在于用一个通道区分所有类别前背景还是让每个通道负责对应类别的前背景，效果可能有些区别。具体怎样可以自己对比一下

**Comment by sdu-huanhq** [comment]
> 区别在于用一个通道区分所有类别前背景还是让每个通道负责对应类别的前背景，效果可能有些区别。具体怎样可以自己对比一下

预测前背景的话用只用mask可以吗？为什么xyz map和region中都要加入预测前背景的通道？还烦请王博解答一下：）

**Comment by sdu-huanhq** [comment]
> > 区别在于用一个通道区分所有类别前背景还是让每个通道负责对应类别的前背景，效果可能有些区别。具体怎样可以自己对比一下
> 
> 预测前背景的话用只用mask可以吗？为什么xyz map和region中都要加入预测前背景的通道？还烦请王博解答一下：）

想明白了，这三个参数如果为True的话，就相当于为每一类物体都创建一组单独的xyz_map, mask和region，但如果为false，则所有种类将共享同一个xyz_map, maks和region
