### ISSUE TITLE
Can't download pretrained models

### ISSUE THREAD

**Issue by bobsler** [shanice-l/gdrnpp_bop2022#4]
Hi.

Looks like the pretrained models link is broken, could you check please. 

Thanks.

**Comment by shanice-l** [comment]
Hi,

I've tried to open the link, everything looks fine here.
Could you plz elaborate on the problem, e.g., provide a screenshot?

**Comment by bobsler** [comment]
Thanks for a help, I think maybe problem with my account:
![image](https://user-images.githubusercontent.com/13452879/198652898-0680f484-7c09-402c-8c56-38b0e9fab8bf.png)

**Comment by bobsler** [comment]
Problem only with pretrained models, datasets and output downloads well.
This is from another browser:
![image](https://user-images.githubusercontent.com/13452879/198655331-0077dab8-494e-4ccd-bb7a-440086c2cb4a.png)

**Comment by shanice-l** [comment]
I've created a new link 

https://mailstsinghuaeducn-my.sharepoint.com/:f:/g/personal/liuxy21_mails_tsinghua_edu_cn/EkCTrRfHUZVEtD7eHwLkYSkBCTXlh9ekDteSzK6jM4oo-A?e=6TCh8y 

Give it a try.
