### ISSUE TITLE
depth_factor的含义

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#40]
王博您好
请问在数据集注册时（以lmo_train_pbr为例）计算了```depth_factor = 1000.0 / cam_dict[str_im_id]["depth_scale"]```，请问这个参数的含义是什么，有什么作用？

depth_scale官方给的解释是深度图与这个参数相乘得到真实深度，我不太理解这个depth_factor是用来干什么的？

烦请王博解答：）

**Comment by wangg12** [comment]
乘depth_scale是mm，除depth_factor是m

**Comment by sdu-huanhq** [comment]
> 乘depth_scale是mm，除depth_factor是m
 
明白了，感谢：）
