### ISSUE TITLE
mask_trunc以及crop resize的疑问

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#41]
王博您好：

请问在迭代中处理训练数据的时候，除了mask_visible和mask_full。还有一个mask_trunc参数，请问这个参数的含义是什么？

在对roi使用dzi并resize的时候，我发现在CDPN中考虑了经过尺度变换后bbox超出图像边界的情况，而在gdrnpp中是使用了cv2中的仿射变换函数完成，请问这种方法可以自动处理尺度变换后bbox超出边界的这种情况吗？

烦请王博解答：）

**Comment by sdu-huanhq** [comment]
而且观察到对roi_img和mask在crop_resize的时候使用的差值方法不同，请问这样做的目的是什么？

**Comment by wangg12** [comment]
mask trunc 是对其做了裁剪增广的结果。仿射变换函数自动处理边界情况，和CDPN手动处理边界的应该是一致的（但是手动处理比较麻烦，出错几率更大）。一般来说，对img用线性插值，对mask做最近邻插值效果更好，你可以实际实验对比一下。

**Comment by sdu-huanhq** [comment]
Thank you very much for Dr. Wang's patient and meticulous answer!
非常感谢王博耐心细致的回答
