### ISSUE TITLE
bop_render无法使用

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#42]
王博您好：

在test的时候，好像需要使用到bop_render，我在project的根目录发现了名为```bop_render```的文件，但貌似是个软链接。

我在```https://github.com/thodan/bop_renderer```中找到了bop_render并按照教程成功编译，但运行test时仍提示```AttributeError: module 'bop_renderer' has no attribute 'Renderer'```

我尝试导入bop_render编译生成的so文件，但提示file too short的错误，请王博指点一下这个bop_render该怎么导入？

下面是我的Project的文件结构和编译后的bop_render文件夹结构以及导入so文件的错误（我import的so文件所在的路径为```bop_renderer/build/bop_renderer.cpython-37m-x86_64-linux-gnu.so```）
![image](https://user-images.githubusercontent.com/57307657/225857843-bd003e91-d7f8-4cbe-89ea-867d2ed213d6.png)

![image](https://user-images.githubusercontent.com/57307657/225857922-c19af5a4-28e1-45f2-954f-a70a6f0a641a.png)

![image](https://user-images.githubusercontent.com/57307657/225859242-46c1adb5-5f97-42ac-93ab-a10861439b74.png)

烦请王博解答：）

**Comment by sdu-huanhq** [comment]
so文件编译出来的大小为0，不知道哪里出问题，先找找看：（

**Comment by sdu-huanhq** [comment]
已解决，注意需要提前将LLVM的lib库导入到环境变量中，参考#32 

王博perfect

**Comment by haicaoha** [comment]
我也有这个问题AttributeError: module 'bop_renderer' has no attribute 'Renderer'，不过我已经成功编译bop_renderer并创建了软连接
![image](https://github.com/shanice-l/gdrnpp_bop2022/assets/81907917/0b9411f5-5ddb-407e-bbef-65ccde74a79a)

**Comment by tan-tao11** [comment]
请问这个问题是如何解决的，我也遇到了？

> 我也有这个问题AttributeError: module 'bop_renderer' has no attribute 'Renderer'，不过我已经成功编译bop_renderer并创建了软连接 ![image](https://private-user-images.githubusercontent.com/81907917/287628663-0b9411f5-5ddb-407e-bbef-65ccde74a79a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NTIyMDAsIm5iZiI6MTcyMjc1MTkwMCwicGF0aCI6Ii84MTkwNzkxNy8yODc2Mjg2NjMtMGI5NDExZjUtNWRkYi00MDdlLWJiZWYtNjVjY2RlNzRhNzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA2MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNWViOTYyM2RlYzZlN2JlNWE0NDY3OTk2MTI3MTJmNTI1OWRhNDQ0YTE3NTZiYTgyMTE5ZGZmMzRlNzA0YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3DM0t08FGr42UqlpPGHW2SOfS9eiZ9WdLHYNZ_u2KLM)
