### ISSUE TITLE
refine时出现的错误

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#43]
王博您好：

在对lmo进行refine的过程中出现了Keyerror “coor_x”的错误

![image](https://user-images.githubusercontent.com/57307657/226152415-b399c776-27d6-4688-89ec-33f0504daf4d.png)

我看到#8 中也提到了相关错误，但至今仍未解决
 
我使用的命令行为（gdrnpp_double_mask模型）：

```./core/gdrn_modeling/test_gdrn_depth_refine.sh configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05mlL1_DMask_amodalClipBox_classAware_lmo.py 2 output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/model_0223929.pth```

烦请王博解答：）

**Comment by sdu-huanhq** [comment]
烦请解答一下，万分感谢：） @lolrudy

**Comment by shanice-l** [comment]
是bug，已经修复

**Comment by sdu-huanhq** [comment]
感谢刘博：）
