### ISSUE TITLE
geo_head中的一个bug？

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#45]
王博，刘博您好：
在geo_head的```TopDownDoubleMaskXyzRegionHead```中，我打印了一下self.feature变量，发现ConvModule中两次GN，如下图所示：
![image](https://user-images.githubusercontent.com/57307657/226594085-3ac2e5cb-2906-4cae-aafb-d0b120273363.png)

**Comment by sdu-huanhq** [comment]
将```lib/torch_utils/layers/conv_module.py```中```self.add_module(self.norm_name, self.norm)```注释掉即可

**Comment by sdu-huanhq** [comment]
将```lib/torch_utils/layers/conv_module.py```中```self.add_module(self.norm_name, self.norm)```注释掉即可

**Comment by wangg12** [comment]
可能是有，不过感觉应该影响不大。

**Comment by sdu-huanhq** [comment]
好的，感谢王博：）
