### ISSUE TITLE
关于旋转变换的一点疑问

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#46]
王博您好，
在```core/utils/utils.py```中的```allo_to_ego_mat_torch```函数，利用该函数对旋转进行变换，请问这个函数有什么作用呢？我没太看懂。烦请王博解答：）

**Comment by wangg12** [comment]
就是论文里说的，预测的是allocentric的表示，变到egocentric下算loss

**Comment by sdu-huanhq** [comment]
感谢王博的解答：）
