### ISSUE TITLE
关于nominal batch size的疑问

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#47]
王博您好：
在config文件中有```REFERENCE_BS```这个参数，您在```core/gdrn_modeling/engine/engine.py```中的注释为nominal batch size

我通过查资料知道nominal batch size的含义为名义批次,比如实际批次为16,那么64/16=4,每4次迭代，才进行一次反向传播更新权重，在代码中您使用了accumulate_iter这个变量表示

但在代码中发现网络的参数是每次迭代都更新的，与accumulate_iter无关，但梯度每accumulate_iter个迭代才清零，这样做的效果会更好吗？

![image](https://user-images.githubusercontent.com/57307657/228199080-cf5c762f-6b77-4e56-bcfc-afd39d5ab8d1.png)

按理说应该每accumulate_iter个迭代进行模型参数更新和梯度清零吧

烦请王博解答：）

**Comment by wangg12** [comment]
这块参考的yolo里面的代码，你可以check下他们的实现，我们这里实际没用这个功能

**Comment by wangg12** [comment]
是的，应该是写错了

**Comment by sdu-huanhq** [comment]
感谢王博解答
