### ISSUE TITLE
models_info.json

### ISSUE THREAD

**Issue by mateen-pz** [shanice-l/gdrnpp_bop2022#48]
helloo,
i'm running this repo on pretrained model when i run the command it show me models_info.json where i can find that?

**Comment by mateen-pz** [comment]
okay thank you i find it. 
one more think is train pbr require for testing?

**Comment by shanice-l** [comment]
No, if you want to test the model only, PBR data is not necessary.
But you have to change the configs (cfg.DATASETS.TRAIN) or the code won't run smoothly.
