### ISSUE TITLE
关于训练期间保存可视化数据的一点小问题

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#50]
王博您好：
在训练期间进行可视化保存的过程中（`core/gdrn_modeling/engine/engine.py`文件的`self.do_train()`函数中的`if cfg.TRAIN.VIS_IMG:`部分）：
1. 需要在`tbx_writer.add_image`中添加`dataformats="HWC"`，否则将出现`Cannot handle this data type: (1, 1, 256), |u1`的错误
2. 在训练期间，out_dict的输出为一个空的字典，如果进行可视化的将报错。需要在前向传播的时候把`coor_x, coor_y, coor_z`等变量添加到out_dict中去才可以（类似test过程中out_dict的更新）

**Comment by wangg12** [comment]
`(1, 1, 256)`是什么数据，可能是数据本身不太对，需要过滤

`coor_x, coor_y, coor_z`要可视化的话你可以自己加一下，当时不加可能是考虑到训练时可视化图片速度会比较慢

**Comment by sdu-huanhq** [comment]
> `(1, 1, 256)`是什么数据，可能是数据本身不太对，需要过滤
> 
> `coor_x, coor_y, coor_z`要可视化的话你可以自己加一下，当时不加可能是考虑到训练时可视化图片速度会比较慢

图像的数据是[256,256,3]没有错，但如果不加dataformats="HWC"的话就会这个错，不知道为什么
感谢王博解答：）
