### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by ustblogistics87** [shanice-l/gdrnpp_bop2022#51]
两位博士好，在复现工作的时候遇到关于训练时长的问题，想请教一下是否正常
两张RTX3090，在ycbv全物体上训练大概需要14天。
在tless(Pbr)单物体上训练大概需要16小时(IMS_PER_BATCH=48)。
参见https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/tools/lm/lm_pbr_1_gen_xyz_crop.py
进行离线渲染，对tless数据集进行xyzcrop生成，但是生成到大概五分之四就已经占用了400G硬盘内存。
由此想问一下这样的训练时长是否正常，如果正常的话，如何能提高一些训练速度呢？

期待回复！谢谢！

**Comment by wangg12** [comment]
多加机器和卡吧，我也没啥好办法， @shanice-l 有啥其他建议么

**Comment by shanice-l** [comment]
ycbv全物体上训练20-30左右epoch就够了，config为了统一多写了一点

**Comment by ustblogistics87** [comment]
抱歉回复较晚。
感谢两位博士的解答，按照您的设置参数如下，其他参数和master分支保持一致(ycbv全物体epoch设置为20)
IMS_PER_BATCH=40, #48单卡显存不够
TOTAL_EPOCHS=20
TRAIN=("ycbv_train_real", "ycbv_train_pbr")
单张3090显示eta需要训练10天，是否是估计有问题呢？但是我之前确实训练了三天，的确按照百分比是需要10天-12天的。
![image](https://user-images.githubusercontent.com/50019289/230278217-5043006f-2bc6-4207-b8c5-f7ba910ec25a.png)
期待回复！谢谢！

**Comment by shanice-l** [comment]
可能跟cpu的性能有关系，这个速度瓶颈主要在dataloader加载数据的过程，试试增加Num_workers可能好一些

**Comment by ustblogistics87** [comment]
好的，可能是和cpu性能有关系，增加num_workers到16之后有显著的性能提升。感谢您的回答~

**Comment by wangg12** [comment]
pytorch 2.0的compile也许能再加点速
