### ISSUE TITLE
test_bboxes

### ISSUE THREAD

**Issue by Martin9797** [shanice-l/gdrnpp_bop2022#53]
Hi, in the README.md you put the instruction to download the folder 'test_bboxes' for each respective dataset. Could you explain what exactly those files are for? And is there a way to obtain it for a custom dataset? I have already trained yolox with that dataset, so is there a way to generate these .json files?

Thank you for your help!

**Comment by wangg12** [comment]
The files are used for providing test bounding boxes for the pose estimator.

I previously used https://github.com/THU-DA-6D-Pose-Group/self6dpp/blob/main/det/yolov4/tools/convert_det_results_to_bop.py to generate the json files based on the inference results. But it seems such a script is not included in this repo. Perhaps you can give it a try.

**Comment by shanice-l** [comment]
The test bounding boxes are used for test-time zoom-in. Here is a [script](https://github.com/shanice-l/gdrnpp_bop2022/blob/main/core/gdrn_modeling/tools/lmo/convert_lmo_det_to_ours.py) you can refer to for transferring bounding box to bop format.
