### ISSUE TITLE
关于crop后相机内参变化的问题

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#54]
王博您好：
在`core/utils/camera_geometry.py`中的`get_K_crop_resize`函数是对crop和resize后的图像进行内参变换, 在下方标注红框的代码中, 我看网上都是用下面的公式计算的

`new_K[:, [0, 1], 2] = 原图像的主点坐标-(原图像size-crop后图像的size)/2`

而您使用了`原图像的主点坐标-bbox的左上角坐标`, 请问为什么要这么做呢

如果crop是在原图的右下角, 那么这个值就应该是负数了呀, 内参怎么会有负数呢?
![image](https://user-images.githubusercontent.com/57307657/230305477-eb24188a-a5cf-47cd-88c4-29d611dfcf81.png)

**Comment by wangg12** [comment]
不清楚您说的是哪个“网上”。我是自己推导的，简单算一下就可以：

假设原图像点(u, v)^T, 在crop上的点为(u', v')^T=(u - left, v - top)^T，3D点为(X, Y, Z)^T

那么

u' = fxX/Z + cx - left

v' = fyY/Z + cy - top

==>

cx' = cx - left

cy' = cy - top

和代码是一致的。

**Comment by sdu-huanhq** [comment]
感谢王博的解答, 非常抱歉上面提到的那个公式是中心裁剪用的, 十分抱歉
![1E1600D4](https://user-images.githubusercontent.com/57307657/230325423-bbd0d397-89e0-40cd-842d-f500453a363c.png)

非常非常感谢!!
