### ISSUE TITLE
加速训练时的渲染速度

### ISSUE THREAD

**Issue by sdu-huanhq** [shanice-l/gdrnpp_bop2022#58]
王博您好：
请问有什么方法可以加速训练过程的渲染速度吗（2D-3Dmap生成）？

**Comment by sdu-huanhq** [comment]
目前在TOTAL_epoch=40，num_workers=8的设置下使用3090训练linemod大概需要四天的时间

**Comment by wangg12** [comment]
目前这个速度已经是我所知的最快的了

**Comment by sdu-huanhq** [comment]
> 目前这个速度已经是我所知的最快的了

好的, 感谢王博
