### ISSUE TITLE
Pretrained weights inside gdrn cannot be extracted 

### ISSUE THREAD

**Issue by francescosarno** [shanice-l/gdrnpp_bop2022#62]
I followed the link to the OneDrive folder and I downloaded the weights of both yolox and gdrn. However, while yolox folder can be unzipped, gdrn cannot. Do you know how to solve this?

**Comment by shanice-l** [comment]
Has anyone else met this situation before?

**Comment by nafisehnamazypour** [comment]
I followed the link to the OneDrive folder and I downloaded the trained models. But when I want to extract it, it gives me the error that the file has a problem.

**Comment by shanice-l** [comment]
I think the reason is that the folder is too big.

Downloading the models separately might fix the problem.

**Comment by harisanthanamagility** [comment]
Has anybody been able to resolve this issue?
