### ISSUE TITLE
pytorch_lightning.lite

### ISSUE THREAD

**Issue by godfatherqyx** [shanice-l/gdrnpp_bop2022#63]
![image](https://github.com/shanice-l/gdrnpp_bop2022/assets/53429443/4b39f5cc-aace-4c5f-ad1d-326ab3c7b9f4)
![image](https://github.com/shanice-l/gdrnpp_bop2022/assets/53429443/64f7279f-8ca7-4d05-a2c9-a683fb4f8493)

I have successfully installed pytorch_lightning via pip, but can't find module pytorch_lightning.lite which puzzled me .

my package versions are as follows:
python                3.9.0
torch                   1.11.0+cu113
pytorch-lightning       2.0.0
CUDA                  11.3

**Comment by shanice-l** [comment]
You can delete this line. No side effects will be made for experiments.

**Comment by godfatherqyx** [comment]
Thank you for your prompt reply!

**Comment by Sar-thak-3** [comment]
Hi @shanice-l pytorch_lightning.lite also imported at 
https://github.com/shanice-l/gdrnpp_bop2022/blob/8c6c34b1705008c6798f921dc5609f1e77f045e2/core/gdrn_modeling/engine/engine.py#L28
