### ISSUE TITLE
Bop challenge

### ISSUE THREAD

**Issue by Martin9797** [shanice-l/gdrnpp_bop2022#64]
When implementing only the main branch and training for each object of a dataset separately,  which exact version of GDRNPP from the bop challenge leaderboard do you get? The GDRNPP-PBRReal-RGBD-MModel-Fast?

**Comment by shanice-l** [comment]
You got the results of GDRNPP-PBRReal-RGB-MModel.

We implement depth as the extra information for refinement. Please look the depth_refine branch for details.

**Comment by Martin9797** [comment]
So fast refinement (`./core/gdrn_modeling/test_gdrn_depth_refine.sh <config_path> <gpu_ids> <ckpt_path> (other args)`)also needs the depth_refine branch for implementation?

**Comment by shanice-l** [comment]
No. The fast refinement procedure has been integrated into the main branch.

**Comment by shanice-l** [comment]
See [README.md](https://github.com/shanice-l/gdrnpp_bop2022#pose-refinement) for details.

**Comment by Martin9797** [comment]
So by using the command `./core/gdrn_modeling/test_gdrn_depth_refine.sh <config_path> <gpu_ids> <ckpt_path> (other args)` I would get the results of GDRNPP-PBRReal-RGBD-MModel-Fast?

**Comment by shanice-l** [comment]
Yes, that's ture.
