### ISSUE TITLE
compile_cpp_egl_renderer.sh失败

### ISSUE THREAD

**Issue by guan2000910** [shanice-l/gdrnpp_bop2022#65]
运行sh lib/egl_renderer/compile_cpp_egl_renderer.sh 面临错误： Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_egl_LIBRARY
  OpenGL EGL)
Call Stack (most recent call first):
我想问CMakelist需要进行修改吗？使用的是Ubuntu-16.04，没有用docker环境，还是说docker环境是必须的？每次遇到Opengl就会产生一些问题。

**Comment by guan2000910** [comment]
这个问题好像解决了，但是又遇到了和gdr_net一样的egl初始化问题。
当我运行./core/gdrn_modeling/train_gdrn.sh configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py 0,1的时候：
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: EGLError(
        err = EGL_NOT_INITIALIZED,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7f2fb81e0740>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)

**Comment by shanice-l** [comment]
gdrnpp只在ubunbtu20.04和18.04上测试过，docker环境不是必须的。
