### ISSUE TITLE
Evaluation failed, folder for vsd evaluation in output seems to be missing after training

### ISSUE THREAD

**Issue by beastGrendel** [shanice-l/gdrnpp_bop2022#67]
Good day,

when finishing the training of GDRNPP I am encountering an error with the egl-renderer. It throws the info, that a .txt flies does not exist (gdrnpp_bop2022/lib/egl_renderer/robotPose/panda_arm_models/models.txt), followed by an info, that the pose error could not be determined. Then, it goes through two tests (both called "ape-iter0_lmo-test"), one per objects "mspd_5:50" and "mssd_0.050:0.500"
, which is followed by another runtime error specifying the output folder "RuntimeError: output/gdrn/lmoPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_lmo/ape/inference_/lmo_bop_test/ape-iter0_lmo-test/error:vsd_ntop:1_delta:15.000_tau:0.050 does not exist." 

I do not know, how to handle this error, any tips? Am I missing something from the bop_toolkit perhaps? (trying "cpp" as render option in the lmo config file produces a similar issue, where the module bop_renderer was not found)

Kind regards,

**Comment by shanice-l** [comment]
Check if bop_renderer is rightly compiled.

**Comment by beastGrendel** [comment]
Thanks for the swift reply. I reinstalled the bop_toolkit and compiled the bop_renderer, too. And, this seems to have fixed the renderer issue.

The other issue prevails, though. It has something to do with the "vsd" evaluation metric, since the corresponding folder (as detailed in my original post) is not existent in the output folder after training. I did not change anything else in the main training script, except reducing the number of folders processed in the dataset as well as the batch size and epochs, since I wanted to test the pipeline for errors, first.

**Comment by beastGrendel** [comment]
I was able to find the issue, I linked the bop_renderer in a different file than in lib/physixd/config.py

**Comment by AmanSriv97** [comment]
Hello @shanice-l ,

I have an error that is similar to what @beastGrendel shared above. When I load the pre-trained weights for LMO dataset and try to do testing for Pose Estimation, then I am getting this error .

RuntimeError: output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/lmo_bop_test/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test/error:vsd_ntop:1_delta:15.000_tau:0.050 does not exist.

I am unable to get past this issue. Kindly guide me what to do. I have also re installed and compiled bop_renderer.

![Screenshot from 2023-12-20 19-50-20](https://github.com/shanice-l/gdrnpp_bop2022/assets/110150684/3abb79c6-0acb-4f9b-bbdf-e83424eb948f)
