### ISSUE TITLE
Hello, is your pre training model damaged?

### ISSUE THREAD

**Issue by Kiansmi** [shanice-l/gdrnpp_bop2022#7]
When training the detector, I will encounter the following errors. Is the pre training model you uploaded incomplete or damaged?

For example, if I run the following statement, an error will occur:

init_checkpoint = "./pretrained_models/yolox/yolox_x.pth"
torch.load(init_checkpoint,map_location=torch.device("cuda"))

Traceback (most recent call last):
  File "gdrnpp_bop2022/det/yolox/tools/boardtest.py", line 6, in <module>
    torch.load(init_checkpoint,map_location=torch.device("cuda"))
  File "/home/dell/anaconda3/envs/gdrn/lib/python3.8/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/dell/anaconda3/envs/gdrn/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by akshay-bapat-magna** [comment]
Hi, I am facing the same issue. Do you have any updates @Rainbowend, @shanice-l or @Kiansmi?

**Comment by shanice-l** [comment]
Sry, maybe an error occurred during transferring of files. Now I've reuploaded it.

Please recheck it.

**Comment by akshay-bapat-magna** [comment]
Thank you @shanice-l, it works now. But just a note for anyone who is facing the same issue - even with the updated model, Ubuntu was having a problem downloading it correctly. I downloaded on Windows and then transferred to the Ubuntu machine and that is when it started working.

**Comment by wangg12** [comment]
> Sry, maybe an error occurred during transferring of files. Now I've reuploaded it.
> 
> Please recheck it.

I think it would be better to also upload the sha256sum of each file so that one can check the correctness of the files easily.
