### ISSUE TITLE
About generalization ability

### ISSUE THREAD

**Issue by lzt02** [shanice-l/gdrnpp_bop2022#73]
What is the generalization ability of the project, and does it need to be trained separately for different categories, or only once for the entire data set？

Thank you in advance for your answers.

**Comment by shanice-l** [comment]
Actually, training a single model for one dataset will lead to a performance drop (AR_bop metric 67.8 v.s.72.8). According to experiments, enlarging the backbone capacity would eliminate this phenomenon to some extent.
