### ISSUE TITLE
RuntimeError: Could not import backend "EGL":Could not initialize

### ISSUE THREAD

**Issue by wwzhizhuo** [shanice-l/gdrnpp_bop2022#75]
刘博，您好！我在测试快速深度细化时使用了以下的代码：
`./core/gdrn_modeling/test_gdrn_depth_refine.sh configs/gdrn/itodd_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_itodd.py 0 ./output/gdrn/model_final_wo_optim.pth`
但是遇到“EGL”无法初始化的问题，详情如下：
` File "/root/miniconda3/envs/gdnpp/lib/python3.8/site-packages/vispy/app/application.py", line 47, in __init__
    self._use(backend_name)
    │    │    └ 'egl'
    │    └ <function Application._use at 0x7f1694cb8f70>
    └ <Vispy app with no backend>
  File "/root/miniconda3/envs/gdnpp/lib/python3.8/site-packages/vispy/app/application.py", line 240, in _use
    raise RuntimeError(msg)
                       └ 'Could not import backend "EGL":\nCould not initialize'

RuntimeError: Could not import backend "EGL":Could not initialize`
希望您可以帮忙解答下！

**Comment by shanice-l** [comment]
请检查egl renderer是否正确安装

**Comment by wwzhizhuo** [comment]
> 请检查egl renderer是否正确安装

感谢刘博，egl renderer已经正确安装，这可能与服务器的环境有关，利用MobaXterm的X11链接可以解决此问题

**Comment by shanice-l** [comment]
好的，多谢
