### ISSUE TITLE
Does GDRNPP support Single-class object with multiple instances poses?

### ISSUE THREAD

**Issue by minghui97** [shanice-l/gdrnpp_bop2022#77]
For my dataset, there are multiple same objects in a bin, would the algorithm work? Appreciate.

**Comment by shanice-l** [comment]
Yes, it will work. Plz refer to the experiment results on the ICBIN dataset.

**Comment by minghui97** [comment]
大佬你好，我现在用GDRNPP识别工业零件做robotic bin picking，在注册自己的dataset时遇到些问题，有些地方不太清楚，方便加个微信沟通一下吗？非常感谢！VX：hmh1997222.
