### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Missing key train

### ISSUE THREAD

**Issue by hrkita** [shanice-l/gdrnpp_bop2022#82]
![2023-11-30 19-34-21 的屏幕截图](https://github.com/shanice-l/gdrnpp_bop2022/assets/151819171/0fdeaba7-0330-485c-9f34-2a0f72ea9278)
 你好，想请问，我在运行这行命令时./det/yolox/tools/train_yolox.sh configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py 0
 报错说我缺少train关键字应该怎么解决呢？因为没有接触过yolox

**Comment by wangg12** [comment]
you were using the wrong config.
