### ISSUE TITLE
如何仅利用RGB图像进行训练

### ISSUE THREAD

**Issue by wwzhizhuo** [shanice-l/gdrnpp_bop2022#86]
刘博，您好：
我定义了自己的RGBD数据集，并且可以跑通您提供的代码。但是现在我们想要尝试一下，仅使用RGB图像进行训练和测试，这个应该如何设置程序的入口。希望您帮忙解答下，感谢您的回复！

**Comment by shanice-l** [comment]
只有refinement需要depth

**Comment by wwzhizhuo** [comment]
好的，感谢刘博！
