### ISSUE TITLE
Runtime error :- error:vsd_ntop:1_delta:15.000_tau:0.050 does not exist.

### ISSUE THREAD

**Issue by AmanSriv97** [shanice-l/gdrnpp_bop2022#88]
Hello @shanice-l ,

I have an error that is similar to what @beastGrendel shared in #67. When I load the pre-trained weights for LMO dataset and try to do testing for Pose Estimation, then I am getting this error .

RuntimeError: output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/lmo_bop_test/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test/error:vsd_ntop:1_delta:15.000_tau:0.050 does not exist.

I am unable to get past this issue. Kindly guide me what to do. I have also re installed and compiled bop_renderer as you mentioned in that issue.
![Screenshot from 2023-12-20 19-50-20](https://github.com/shanice-l/gdrnpp_bop2022/assets/110150684/ccb14bc7-7fa1-4d29-8854-7d4cf5475514)

**Comment by shanice-l** [comment]
You should build bop_renderer at first.

**Comment by AmanSriv97** [comment]
Thanks the error got solved.

**Comment by wangg12** [comment]
> > Thanks the error got solved.
> 
> Hi, I met the same issue and rebuilt the bop_renderer again. However, I cannot solve the problem. Could you please give me more explanation?

Now you can change the renderer to `vispy` to get rid of errors caused by bop_renderer. See https://github.com/thodan/bop_toolkit?tab=readme-ov-file#vispy-renderer-default
