### ISSUE TITLE
Produce detectron2 compatible input data from synthetic data generated by blenderproc2.

### ISSUE THREAD

**Issue by tzsombor95** [shanice-l/gdrnpp_bop2022#9]
Hi,

I created a custom dataset with [https://github.com/DLR-RM/BlenderProc/blob/main/README_BlenderProc4BOP.md](url), to train a custom model with the help of this repository.
Is there any way or script that I can use the data generated by the above tool to produce the input format needed to train detectron2.

If not, can you point me to an exact folder and data structure description on how I can run the train script?
My last message was: "AssertionError: Dataset 'lmo_pbr_train' is empty!", but I don't know exactly what to put here and in what format.

Many thanks for your help!

**Comment by wangg12** [comment]
Hi,

We usually write a dataset class for converting any custom formats like blenderproc into detectron2 format. For a reference, you could convert you own dataset like what we did in https://github.com/shanice-l/gdrnpp_bop2022/blob/main/core/gdrn_modeling/datasets/lm_pbr.py.
